//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Full_Contract
    {
        public int ID { get; set; }
        public string FullContractCode { get; set; }
        public string CustomerName { get; set; }
        public Nullable<int> YearOfBirth { get; set; }
        public string SSN { get; set; }
        public string CustomerAddress { get; set; }
        public string Mobile { get; set; }
        public Nullable<int> PropertyID { get; set; }
        public Nullable<System.DateTime> DateOfContract { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<int> Deposit { get; set; }
        public Nullable<int> Remain { get; set; }
        public Nullable<bool> Status { get; set; }
    
        public virtual Property Property { get; set; }
    }
}
