//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Property()
        {
            this.Full_Contract = new HashSet<Full_Contract>();
            this.Installment_Contract = new HashSet<Installment_Contract>();
            this.Property_Service = new HashSet<Property_Service>();
        }
    
        public int ID { get; set; }
        public string PropertyCode { get; set; }
        public string PropertyName { get; set; }
        public Nullable<int> PropertyTypeID { get; set; }
        public string Description { get; set; }
        public Nullable<int> DistrictID { get; set; }
        public string Address { get; set; }
        public Nullable<int> Area { get; set; }
        public Nullable<int> BedRoom { get; set; }
        public Nullable<int> BathRoom { get; set; }
        public Nullable<int> Price { get; set; }
        public Nullable<double> InstallmentRate { get; set; }
        public string Avatar { get; set; }
        public string Album { get; set; }
        public Nullable<int> PropertyStatusID { get; set; }
    
        public virtual District District { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Full_Contract> Full_Contract { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Installment_Contract> Installment_Contract { get; set; }
        public virtual Property_Status Property_Status { get; set; }
        public virtual Property_Type Property_Type { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Property_Service> Property_Service { get; set; }
    }
}
